/mob/living/simple_animal/hostile/ubermorph
	name = "Ubermorph"
	desc = "A juvenile hivemind. Constantly regenerating, a nigh-immortal leader of the necromorph army."
	icon = 'Minti_modular/code/modules/mob/necro/ubermorph.dmi'
	icon_state = "ubermorph"
	icon_living = "ubermorph"
	icon_dead = "ubermorph"
	mob_biotypes = MOB_ORGANIC|MOB_BEAST
	mouse_opacity = MOUSE_OPACITY_ICON
	friendly_verb_continuous = "stares at"
	friendly_verb_simple = "stares at"
	speak_emote = list("screams")
	speed = 5
	move_to_delay = 5
	maxHealth = 250000000
	health = 250000000
	obj_damage = 50
	melee_damage_lower = 25.5
	melee_damage_upper = 25.5
	rapid_melee = 4 // every second attack
	dodging = TRUE
	dodge_prob = 50
	attack_verb_continuous = "slashes"
	attack_verb_simple = "slash"
	attack_sound = 'sound/weapons/bladeslice.ogg'
	vision_range = 8
	aggro_vision_range = 8
	move_force = MOVE_FORCE_WEAK
	move_resist = MOVE_FORCE_WEAK
	pull_force = MOVE_FORCE_WEAK
	butcher_results = list(/obj/item/reagent_containers/food/snacks/meat/slab = 2)
	stat_attack = UNCONSCIOUS
	robust_searching = TRUE
