# Конфигурация Автомаппера
# [templates.example_template] - example_template должно быть заменено на название вашего шаблона.
# directory - путь к *папке* в которой находится нужный *.dmm файл.
# map_files - название самого файла. Можно вписать несколько, тогда будет выбран рандомный.
# required_map - название файла "мапы", который должен быть загружен, чтобы шаблон ваш шаблон был инициализирован.
# coordinates - координаты *внутри сектора*, в которых будет расположен данный шаблон. Z-координата - отвечает за этаж.
# trait_name - название трейта, по которому будет найден нужный сектор.

# Основные трейты - Station (сектор станции), CentCom (сектор ЦК), Mining (лаваленд)
# Подробнее в code\__DEFINES\maps.dm

# С примерами можете ознакомится в _maps\skyrat\automapper\automapper_config.toml

# С помощью коммент-тега(!) #UNREG=template_name вы можете исключить загрузку определённого шаблона.
# Вместо template_name вставьте название шаблона, которое идёт после "templates."
# Данный коммент-тег ОБЯЗАТЕЛЬНО должен быть в начале отдельной строкой.

